#!/usr/bin/env python3
"""Extract OPERA export blocks and write Markdown capture notes.

Usage:
    python scripts/opera_capture.py input.txt
    python scripts/opera_capture.py input.txt --output-root vault/OPERA-Capture
    python scripts/opera_capture.py --dry-run < input.txt

The parser is deliberately simple: it expects the structured block generated by
the OPERA conversational workflow and converts it into a stable Markdown note.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


BEGIN = "[OPERA_EXPORT_BEGIN]"
END = "[OPERA_EXPORT_END]"


@dataclass
class OperaCapture:
    identifier: str
    date: str
    capture_type: str
    done: list[str] = field(default_factory=list)
    next_actions: list[str] = field(default_factory=list)
    waiting: list[str] = field(default_factory=list)
    calendar: list[str] = field(default_factory=list)
    research_state: list[str] = field(default_factory=list)


def extract_block(text: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN) + r"(.*?)" + re.escape(END),
        re.DOTALL,
    )
    match = pattern.search(text)
    if not match:
        raise ValueError("No OPERA export block found.")
    return match.group(1).strip()


def parse_block(block: str) -> OperaCapture:
    scalar_fields = {
        "ID": "identifier",
        "Date": "date",
        "Type": "capture_type",
    }
    list_fields = {
        "Done": "done",
        "Next": "next_actions",
        "Waiting": "waiting",
        "Calendar": "calendar",
        "Research state": "research_state",
    }

    values: dict[str, str | list[str]] = {
        "identifier": "",
        "date": "",
        "capture_type": "",
        "done": [],
        "next_actions": [],
        "waiting": [],
        "calendar": [],
        "research_state": [],
    }

    current_list: str | None = None

    for raw_line in block.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        scalar_match = re.match(r"^(ID|Date|Type):\s*(.+)$", line)
        if scalar_match:
            key, value = scalar_match.groups()
            values[scalar_fields[key]] = value.strip()
            current_list = None
            continue

        list_match = re.match(r"^(Done|Next|Waiting|Calendar|Research state):\s*$", line)
        if list_match:
            current_list = list_fields[list_match.group(1)]
            continue

        item_match = re.match(r"^-\s*(.+)$", line)
        if item_match and current_list:
            cast_list = values[current_list]
            assert isinstance(cast_list, list)
            cast_list.append(item_match.group(1).strip())
            continue

        raise ValueError(f"Cannot parse line: {raw_line!r}")

    capture = OperaCapture(
        identifier=str(values["identifier"]),
        date=str(values["date"]),
        capture_type=str(values["capture_type"]),
        done=list(values["done"]),
        next_actions=list(values["next_actions"]),
        waiting=list(values["waiting"]),
        calendar=list(values["calendar"]),
        research_state=list(values["research_state"]),
    )

    if not capture.identifier:
        raise ValueError("Missing ID.")
    if not capture.date:
        raise ValueError("Missing Date.")
    if not capture.capture_type:
        raise ValueError("Missing Type.")

    datetime.strptime(capture.date, "%Y-%m-%d")
    return capture


def markdown_list(items: list[str]) -> str:
    if not items:
        return "- none"
    return "\n".join(f"- {item}" for item in items)


def render_markdown(capture: OperaCapture) -> str:
    title = f"{capture.identifier} — {capture.capture_type}"
    return f"""---
id: {capture.identifier}
date: {capture.date}
type: {capture.capture_type}
opera_version: v0.3
---

# {title}

## 1. Cosa ho fatto?

{markdown_list(capture.done)}

## 2. Cosa resta?

{markdown_list(capture.next_actions)}

## 3. C'è qualcosa in attesa?

{markdown_list(capture.waiting)}

## 4. Devo mettere una data su Calendar?

{markdown_list(capture.calendar)}

## 5. Stato della ricerca

{markdown_list(capture.research_state)}
"""


def output_path(output_root: Path, capture: OperaCapture) -> Path:
    date = datetime.strptime(capture.date, "%Y-%m-%d")
    filename = f"{capture.date}-{capture.identifier.lower()}.md"
    return output_root / f"{date:%Y}" / f"{date:%m}" / filename


def main() -> int:
    parser = argparse.ArgumentParser(description="Extract OPERA export blocks.")
    parser.add_argument("input", nargs="?", help="Text file containing an OPERA export block. Reads stdin if omitted.")
    parser.add_argument("--output-root", default="vault/OPERA-Capture", help="Root directory for generated notes.")
    parser.add_argument("--dry-run", action="store_true", help="Print generated Markdown instead of writing a file.")
    args = parser.parse_args()

    source = Path(args.input).read_text(encoding="utf-8") if args.input else sys.stdin.read()
    capture = parse_block(extract_block(source))
    rendered = render_markdown(capture)

    if args.dry_run:
        print(rendered)
        return 0

    path = output_path(Path(args.output_root), capture)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise FileExistsError(f"Refusing to overwrite existing capture note: {path}")
    path.write_text(rendered, encoding="utf-8")
    print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
